url: https://www.theinternetvagabond.com
title: "The Internet Vagabond"
author: "Bill Niblock"

plugins:
  - jekyll-feed

collections:
  topics:
    output: true

defaults:
  -
    scope:
      path: ''
      type: "posts"
    values:
      layout: "corrupt_post"
      author: "Bill Niblock"
  -
    scope:
      path: ''
      type: "topics"
    values:
      layout: "corrupt_index"
      permalink: "/topics/:name"
